# Generated by Django 5.1.3 on 2024-11-24 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmiana', '0002_shift_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ChangeShiftProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('from_shift', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_shift', to='zmiana.shift')),
                ('to_shift', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_shift', to='zmiana.shift')),
            ],
        ),
    ]
