# Generated by Django 5.1.3 on 2024-11-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmiana', '0003_shift_active_changeshiftproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeshiftproposal',
            name='date_of_acceptance',
            field=models.DateField(auto_now=True),
        ),
    ]
