# Generated by Django 5.1.3 on 2024-11-24 09:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmiana', '0004_changeshiftproposal_date_of_acceptance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(fields=('owner', 'date'), name='unique_shift_owner'),
        ),
    ]
